# National Health and Nutrition Examination Survey
Data from 1990-2020

In [1]:
# Libaries
import pandas as pd
import numpy as np
import xport
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

import pymysql
from sqlalchemy import create_engine

import warnings
warnings.filterwarnings('ignore')

In [35]:
pd.set_option('display.max_columns', None)

# Dietarty Data

In [37]:
# 1999-2000
with open(r"C:\Users\ljant\Downloads\DRXTOT.XPT", 'rb') as f: df = xport.to_dataframe(f)
df.to_csv('diet_file_00.csv', index=False)
df_00 = pd.read_csv(r"C:\Users\ljant\Desktop\Ironhack\Projects\Project_2\Raw_datafiles\Diet\diet_file_00.csv")
df_00['year'] = df_00['year'] = 2000

In [38]:
# 2001-2002
with open(r"C:\Users\ljant\Downloads\DRXTOT_B.XPT", 'rb') as f: df = xport.to_dataframe(f)
df.to_csv('diet_file_02.csv', index=False)
df_02 = pd.read_csv(r"C:\Users\ljant\Desktop\Ironhack\Projects\Project_2\Raw_datafiles\Diet\diet_file_02.csv")
df_02['year'] = df_00['year'] = 2002

In [39]:
# 2003-2004
with open(r"C:\Users\ljant\Downloads\DR1TOT_C.XPT", 'rb') as f: df = xport.to_dataframe(f)
df.to_csv('diet_file_04.csv', index=False)
df_04 = pd.read_csv(r"C:\Users\ljant\Desktop\Ironhack\Projects\Project_2\Raw_datafiles\Diet\diet_file_04.csv")
df_04['year'] = df_04['year'] = 2004

In [40]:
# 2005-2006
with open(r"C:\Users\ljant\Downloads\DR1TOT_D.XPT", 'rb') as f: df = xport.to_dataframe(f)
df.to_csv('diet_file_06.csv', index=False)
df_06 = pd.read_csv(r"C:\Users\ljant\Desktop\Ironhack\Projects\Project_2\Raw_datafiles\Diet\diet_file_06.csv")
df_06['year'] = df_06['year'] = 2006

In [41]:
# 2007-2008
with open(r"C:\Users\ljant\Downloads\DR1TOT_E.XPT", 'rb') as f: df = xport.to_dataframe(f)
df.to_csv('diet_file_08.csv', index=False)
df_08 = pd.read_csv(r"C:\Users\ljant\Desktop\Ironhack\Projects\Project_2\Raw_datafiles\Diet\diet_file_08.csv")
df_08['year'] = df_08['year'] = 2008

In [42]:
# 2009-2010
with open(r"C:\Users\ljant\Downloads\DR1TOT_F.XPT", 'rb') as f: df = xport.to_dataframe(f)
df.to_csv('diet_file_10.csv', index=False)
df_10 = pd.read_csv(r"C:\Users\ljant\Desktop\Ironhack\Projects\Project_2\Raw_datafiles\Diet\diet_file_10.csv")
df_10['year'] = df_10['year'] = 2010

In [43]:
# 2011-2012
with open(r"C:\Users\ljant\Downloads\DR1TOT_G.XPT", 'rb') as f: df = xport.to_dataframe(f)
df.to_csv('diet_file_12.csv', index=False)
df_12 = pd.read_csv(r"C:\Users\ljant\Desktop\Ironhack\Projects\Project_2\Raw_datafiles\Diet\diet_file_12.csv")
df_12['year'] = df_12['year'] = 2012

In [44]:
# 2013-2014
with open(r"C:\Users\ljant\Downloads\DR1TOT_H.XPT", 'rb') as f: df = xport.to_dataframe(f)
df.to_csv('diet_file_14.csv', index=False)
df_14 = pd.read_csv(r"C:\Users\ljant\Desktop\Ironhack\Projects\Project_2\Raw_datafiles\Diet\diet_file_14.csv")
df_14['year'] = df_14['year'] = 2014

In [45]:
# 2015-2016
with open(r"C:\Users\ljant\Downloads\DR1TOT_I.XPT", 'rb') as f: df = xport.to_dataframe(f)
df.to_csv('diet_file_16.csv', index=False)
df_16 = pd.read_csv(r"C:\Users\ljant\Desktop\Ironhack\Projects\Project_2\Raw_datafiles\Diet\diet_file_16.csv")
df_16['year'] = df_16['year'] = 2016

In [46]:
# 2017-2020
with open(r"C:\Users\ljant\Downloads\P_DR1TOT.XPT", 'rb') as f: df = xport.to_dataframe(f)
df.to_csv('diet_file_20.csv', index=False)
df_20 = pd.read_csv(r"C:\Users\ljant\Desktop\Ironhack\Projects\Project_2\Raw_datafiles\Diet\diet_file_20.csv")
df_20['year'] = df_20['year'] = 2020

In [47]:
# Getting only the columns I need.
col_decoder = {
    'SEQN' : 'patient_id',
    'year': 'year', 
    'DRXTPROT': 'protein',
    'DRXTFIBE': 'fiber',
    'DRXTSFAT': 'sattuarated_fatty_acids',
    'DRXTMFAT': 'monounsaturated_fatty_acids',
    'DRXTPFAT': 'polyunsaturated_fatty_acids',
    'DRXTCHOL': 'cholesterol',
    'DRXTCARO': 'carotene',
    'DRXTVAIU': 'vitamin_a',
    'DRXTVB1': 'vitamin_b1',
    'DRXTVB2': 'vitamin_b2',
    'DRXTVB6': 'vitamin_b6',
    'DRXTVB12': 'vitamin_b12',    
    'DRXTVC': 'vitamin_c',
    'DRXTVE': 'vitamin_e',
    'DRXTFOLA': 'folate',
    'DRXTCALC': 'calcium',
    'DRXTPHOS': 'phosporus',
    'DRXTMAGN': 'magnesium',
    'DRXTIRON': 'iron',
    'DRXTZINC': 'zinc',
    'DRXTCOPP': 'copper',
    'DRDTSODI': 'sodium',
    'DRXTPOTA': 'potassium',
    'DRXTSELE': 'selenium',
    'DRXTCAFF': 'caffeine',
    'DRXTALCO': 'alcohol',
    'DRD320GW': 'water' 
}
df_00 = df_00[list(col_decoder.keys())].rename(columns=col_decoder)

In [48]:
# Part II
col_decoder = {
    'SEQN' : 'patient_id',
    'year': 'year', 
    'DRXTPROT': 'protein',
    'DRXTFIBE': 'fiber',
    'DRXTSFAT': 'sattuarated_fatty_acids',
    'DRXTMFAT': 'monounsaturated_fatty_acids',
    'DRXTPFAT': 'polyunsaturated_fatty_acids',
    'DRXTCHOL': 'cholesterol',
    'DRXTACAR': 'a_carotene',
    'DRXTBCAR': 'b_carotene',
    'DRXTVARA': 'vitamin_a',
    'DRXTVB1': 'vitamin_b1',
    'DRXTVB2': 'vitamin_b2',
    'DRXTVB6': 'vitamin_b6',
    'DRXTVB12': 'vitamin_b12',    
    'DRXTVC': 'vitamin_c',
    'DRXTATOC': 'vitamin_e',
    'DRXTFOLA': 'folate',
    'DRXTCALC': 'calcium',
    'DRXTPHOS': 'phosporus',
    'DRXTMAGN': 'magnesium',
    'DRXTIRON': 'iron',
    'DRXTZINC': 'zinc',
    'DRXTCOPP': 'copper',
    'DRDTSODI': 'sodium',
    'DRXTPOTA': 'potassium',
    'DRXTSELE': 'selenium',
    'DRXTCAFF': 'caffeine',
    'DRXTALCO': 'alcohol',
    'DRD320GW': 'water' 
}
df_02 = df_02[list(col_decoder.keys())].rename(columns=col_decoder)

In [49]:
# Part III
col_decoder = {
    'SEQN' : 'patient_id',
    'year': 'year',
    'DR1TPROT': 'protein',
    'DR1TFIBE': 'fiber',
    'DR1TSFAT': 'sattuarated_fatty_acids',
    'DR1TMFAT': 'monounsaturated_fatty_acids',
    'DR1TPFAT': 'polyunsaturated_fatty_acids',
    'DR1TCHOL': 'cholesterol',
    'DR1TACAR': 'a_carotene',
    'DR1TBCAR': 'b_carotene',
    'DR1TVARA': 'vitamin_a',
    'DR1TVB1': 'vitamin_b1',
    'DR1TVB2': 'vitamin_b2',
    'DR1TVB6': 'vitamin_b6',
    'DR1TVB12': 'vitamin_b12',    
    'DR1TVC': 'vitamin_c',
    'DR1TATOC': 'vitamin_e',
    'DR1TFOLA': 'folate',
    'DR1TCALC': 'calcium',
    'DR1TPHOS': 'phosporus',
    'DR1TMAGN': 'magnesium',
    'DR1TIRON': 'iron',
    'DR1TZINC': 'zinc',
    'DR1TCOPP': 'copper',
    'DR1TSODI': 'sodium',
    'DR1TPOTA': 'potassium',
    'DR1TSELE': 'selenium',
    'DR1TCAFF': 'caffeine',
    'DR1TALCO': 'alcohol',
    'DR1_320': 'water' 
}

df_04 = df_04[list(col_decoder.keys())].rename(columns=col_decoder)

In [50]:
# Part IV
col_decoder = {
    'SEQN' : 'patient_id',
    'year': 'year', 
    'DR1TPROT': 'protein',
    'DR1TFIBE': 'fiber',
    'DR1TSFAT': 'sattuarated_fatty_acids',
    'DR1TMFAT': 'monounsaturated_fatty_acids',
    'DR1TPFAT': 'polyunsaturated_fatty_acids',
    'DR1TCHOL': 'cholesterol',
    'DR1TACAR': 'a_carotene',
    'DR1TBCAR': 'b_carotene',
    'DR1TVARA': 'vitamin_a',
    'DR1TVB1': 'vitamin_b1',
    'DR1TVB2': 'vitamin_b2',
    'DR1TVB6': 'vitamin_b6',
    'DR1TVB12': 'vitamin_b12',    
    'DR1TVC': 'vitamin_c',
    'DR1TATOC': 'vitamin_e',
    'DR1TFOLA': 'folate',
    'DR1TCALC': 'calcium',
    'DR1TPHOS': 'phosporus',
    'DR1TMAGN': 'magnesium',
    'DR1TIRON': 'iron',
    'DR1TZINC': 'zinc',
    'DR1TCOPP': 'copper',
    'DR1TSODI': 'sodium',
    'DR1TPOTA': 'potassium',
    'DR1TSELE': 'selenium',
    'DR1TCAFF': 'caffeine',
    'DR1TALCO': 'alcohol',
    'DR1_330Z': 'water' 
}

df_06 = df_06[list(col_decoder.keys())].rename(columns=col_decoder)

In [51]:
# Part V
col_decoder = {
    'SEQN' : 'patient_id',
    'year': 'year', 
    'DRQSDIET': 'special_diet',
    'DR1TPROT': 'protein',
    'DR1TSUGR': 'total_sugars',
    'DR1TFIBE': 'fiber',
    'DR1TSFAT': 'sattuarated_fatty_acids',
    'DR1TMFAT': 'monounsaturated_fatty_acids',
    'DR1TPFAT': 'polyunsaturated_fatty_acids',
    'DR1TCHOL': 'cholesterol',
    'DR1TACAR': 'a_carotene',
    'DR1TBCAR': 'b_carotene',
    'DR1TVARA': 'vitamin_a',
    'DR1TVB1': 'vitamin_b1',
    'DR1TVB2': 'vitamin_b2',
    'DR1TVB6': 'vitamin_b6',
    'DR1TVB12': 'vitamin_b12',    
    'DR1TVC': 'vitamin_c',
    'DR1TVD': 'vitamin_d',
    'DR1TATOC': 'vitamin_e',
    'DR1TVK': 'vitamin_k',
    'DR1TFOLA': 'folate',
    'DR1TCHL': 'choline',
    'DR1TCALC': 'calcium',
    'DR1TPHOS': 'phosporus',
    'DR1TMAGN': 'magnesium',
    'DR1TIRON': 'iron',
    'DR1TZINC': 'zinc',
    'DR1TCOPP': 'copper',
    'DR1TSODI': 'sodium',
    'DR1TPOTA': 'potassium',
    'DR1TSELE': 'selenium',
    'DR1TCAFF': 'caffeine',
    'DR1TALCO': 'alcohol',
    'DR1_320Z': 'water' 
}

df_08 = df_08[list(col_decoder.keys())].rename(columns=col_decoder)
df_10 = df_10[list(col_decoder.keys())].rename(columns=col_decoder)
df_12 = df_12[list(col_decoder.keys())].rename(columns=col_decoder)
df_14 = df_14[list(col_decoder.keys())].rename(columns=col_decoder)
df_16 = df_16[list(col_decoder.keys())].rename(columns=col_decoder)
df_20 = df_20[list(col_decoder.keys())].rename(columns=col_decoder)

In [52]:
df_diet = pd.concat([df_00,
                    df_02,
                    df_04,
                    df_06,
                    df_08,
                    df_10,
                    df_12,
                    df_14,
                    df_16,
                    df_20]).reset_index(drop = True)
df_diet

,patient_id,year,protein,fiber,sattuarated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,cholesterol,carotene,vitamin_a,vitamin_b1,vitamin_b2,vitamin_b6,vitamin_b12,vitamin_c,vitamin_e,folate,calcium,phosporus,magnesium,iron,zinc,copper,sodium,potassium,selenium,caffeine,alcohol,water,a_carotene,b_carotene,special_diet,total_sugars,vitamin_d,vitamin_k,choline
0,1.0,2002,31.96,7.41,9.400,9.000,6.400,46.55,119.41,2797.65,1.500,1.550,1.430,2.42,220.64,3.68,297.85,541.30,503.75,126.80,12.18,4.69,0.410,1621.35,1387.70,48.22,0.00,0.00,243.38,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,2002,123.16,36.99,24.340,26.480,11.940,313.95,182.07,4323.62,2.110,3.250,2.900,8.68,119.12,7.06,528.29,925.37,1974.57,502.25,37.29,41.61,2.080,5710.03,4672.48,123.20,530.45,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,2002,40.19,11.16,15.610,19.570,11.840,86.22,418.58,5754.31,1.210,1.430,1.370,1.59,57.95,6.53,270.32,415.27,674.82,172.58,9.78,5.65,0.850,1676.51,1487.16,38.97,35.40,0.00,531.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,2002,56.16,5.45,27.540,20.130,4.670,194.78,42.08,1426.17,0.960,2.230,0.950,4.25,65.85,3.47,137.58,1315.39,1266.80,204.10,5.79,6.72,0.520,1277.31,2245.42,46.72,0.00,0.00,1652.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,2002,97.13,17.28,36.000,60.550,11.350,180.57,901.71,10292.63,2.620,3.050,2.920,6.66,112.19,13.53,749.83,1626.38,1811.55,367.72,27.22,10.17,1.950,3756.36,3743.15,104.65,0.00,34.56,1298.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102357,124818.0,2020,58.05,15.00,62.115,61.034,45.841,220.00,NaN,743.00,1.875,1.779,0.647,1.17,89.30,14.70,531.00,480.00,883.00,186.00,15.08,6.50,0.941,7742.00,1206.00,163.90,242.00,0.00,0.00,9.0,516.0,2.0,278.84,2.3,103.5,144.8
102358,124819.0,2020,67.43,8.30,32.515,24.228,10.880,175.00,NaN,660.00,1.416,1.921,1.421,5.20,93.40,3.52,233.00,1584.00,1545.00,201.00,8.32,8.00,0.534,2870.00,2356.00,78.90,24.00,0.00,225.00,35.0,224.0,2.0,108.36,13.0,17.4,236.8
102359,124820.0,2020,39.32,12.30,15.558,13.070,14.765,84.00,NaN,698.00,1.563,1.761,2.002,6.00,28.20,4.40,486.00,1384.00,1034.00,161.00,16.36,14.09,0.417,2344.00,1212.00,53.50,13.00,0.00,0.00,14.0,395.0,2.0,65.77,7.0,41.4,115.0
102360,124821.0,2020,138.10,6.70,15.733,30.469,20.797,484.00,NaN,165.00,1.270,1.127,1.688,15.67,32.60,9.83,195.00,368.00,1691.00,236.00,8.03,9.97,0.800,4718.00,2898.00,112.50,0.00,0.00,1267.50,345.0,1425.0,2.0,50.57,1.4,105.5,528.7
102361,124822.0,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN

In [54]:
df_diet.to_csv('diet_python.csv', index=False)