# National Health and Nutrition Examination Survey
Data from 1999-2020 | Mental Health Variables

In [1]:
# Libaries
import pandas as pd
import numpy as np
import xport
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

import pymysql
from sqlalchemy import create_engine

import warnings
warnings.filterwarnings('ignore')

In [2]:
pd.set_option('display.max_columns', None)

# Mental Data

In [3]:
# 1999-2000
with open(r"C:\Users\ljant\Downloads\CIQMDEP.XPT", 'rb') as f: df = xport.to_dataframe(f)
df.to_csv('mental_file_00.csv', index=False)
df_00 = pd.read_csv(r"C:\Users\ljant\Desktop\Ironhack\Projects\Project_2\Raw_datafiles\Mental\Mental_file_00.csv")
df_00['year'] = df_00['year'] = 2000

In [4]:
# 2001-2002
with open(r"C:\Users\ljant\Downloads\CIQDEP_B.XPT", 'rb') as f: df = xport.to_dataframe(f)
df.to_csv('mental_file_02.csv', index=False)
df_02 = pd.read_csv(r"C:\Users\ljant\Desktop\Ironhack\Projects\Project_2\Raw_datafiles\Mental\mental_file_02.csv")
df_02['year'] = df_00['year'] = 2002

In [5]:
# 2003-2004
with open(r"C:\Users\ljant\Downloads\CIQDEP_C.XPT", 'rb') as f: df = xport.to_dataframe(f)
df.to_csv('mental_file_04.csv', index=False)
df_04 = pd.read_csv(r"C:\Users\ljant\Desktop\Ironhack\Projects\Project_2\Raw_datafiles\Mental\mental_file_04.csv")
df_04['year'] = df_04['year'] = 2004

In [6]:
# 2005-2006
with open(r"C:\Users\ljant\Downloads\DPQ_D.XPT", 'rb') as f: df = xport.to_dataframe(f)
df.to_csv('mental_file_06.csv', index=False)
df_06 = pd.read_csv(r"C:\Users\ljant\Desktop\Ironhack\Projects\Project_2\Raw_datafiles\Mental\mental_file_06.csv")
df_06['year'] = df_06['year'] = 2006

In [7]:
# 2007-2008
with open(r"C:\Users\ljant\Downloads\DPQ_E.XPT", 'rb') as f: df = xport.to_dataframe(f)
df.to_csv('mental_file_08.csv', index=False)
df_08 = pd.read_csv(r"C:\Users\ljant\Desktop\Ironhack\Projects\Project_2\Raw_datafiles\Mental\mental_file_08.csv")
df_08['year'] = df_08['year'] = 2008

In [8]:
# 2009-2010
with open(r"C:\Users\ljant\Downloads\DPQ_F.XPT", 'rb') as f: df = xport.to_dataframe(f)
df.to_csv('mental_file_10.csv', index=False)
df_10 = pd.read_csv(r"C:\Users\ljant\Desktop\Ironhack\Projects\Project_2\Raw_datafiles\Mental\mental_file_10.csv")
df_10['year'] = df_10['year'] = 2010

In [9]:
# 2011-2012
with open(r"C:\Users\ljant\Downloads\DPQ_G.XPT", 'rb') as f: df = xport.to_dataframe(f)
df.to_csv('mental_file_12.csv', index=False)
df_12 = pd.read_csv(r"C:\Users\ljant\Desktop\Ironhack\Projects\Project_2\Raw_datafiles\Mental\mental_file_12.csv")
df_12['year'] = df_12['year'] = 2012

In [10]:
# 2013-2014
with open(r"C:\Users\ljant\Downloads\DPQ_H.XPT", 'rb') as f: df = xport.to_dataframe(f)
df.to_csv('mental_file_14.csv', index=False)
df_14 = pd.read_csv(r"C:\Users\ljant\Desktop\Ironhack\Projects\Project_2\Raw_datafiles\Mental\mental_file_14.csv")
df_14['year'] = df_14['year'] = 2014

In [11]:
# 2015-2016
with open(r"C:\Users\ljant\Downloads\DPQ_I.XPT", 'rb') as f: df = xport.to_dataframe(f)
df.to_csv('mental_file_16.csv', index=False)
df_16 = pd.read_csv(r"C:\Users\ljant\Desktop\Ironhack\Projects\Project_2\Raw_datafiles\Mental\mental_file_16.csv")
df_16['year'] = df_16['year'] = 2016

In [12]:
# 2017-2020
with open(r"C:\Users\ljant\Downloads\P_DPQ.XPT", 'rb') as f: df = xport.to_dataframe(f)
df.to_csv('mental_file_20.csv', index=False)
df_20 = pd.read_csv(r"C:\Users\ljant\Desktop\Ironhack\Projects\Project_2\Raw_datafiles\Mental\mental_file_20.csv")
df_20['year'] = df_20['year'] = 2020

In [14]:
# Getting only the columns I need.
col_decoder = {
    'SEQN' : 'patient_id',
    'year': 'year',
    'DPQ010': 'q1',
    'DPQ020': 'q2',
    'DPQ030': 'q3',
    'DPQ040': 'q4',
    'DPQ050': 'q5',
    'DPQ060': 'q6',
    'DPQ070': 'q7',
    'DPQ080': 'q8',
    'DPQ090': 'q9'    
}
df_06 = df_06[list(col_decoder.keys())].rename(columns=col_decoder)
df_08 = df_08[list(col_decoder.keys())].rename(columns=col_decoder)
df_10 = df_10[list(col_decoder.keys())].rename(columns=col_decoder)
df_12 = df_12[list(col_decoder.keys())].rename(columns=col_decoder)
df_14 = df_14[list(col_decoder.keys())].rename(columns=col_decoder)
df_16 = df_16[list(col_decoder.keys())].rename(columns=col_decoder)
df_20 = df_20[list(col_decoder.keys())].rename(columns=col_decoder)

In [15]:
df_mental = pd.concat([df_06,
                    df_08,
                    df_10,
                    df_12,
                    df_14,
                    df_16,
                    df_20]).reset_index(drop = True)
df_mental

       patient_id  year   q1   q2   q3   q4   q5   q6   q7   q8   q9
0         31130.0  2006  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1         31131.0  2006  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2         31132.0  2006  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3         31134.0  2006  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4         31139.0  2006  0.0  0.0  0.0  0.0  3.0  1.0  0.0  0.0  0.0
...           ...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
43923    124815.0  2020  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
43924    124817.0  2020  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
43925    124818.0  2020  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
43926    124821.0  2020  3.0  0.0  0.0  2.0  0.0  0.0  0.0  0.0  0.0
43927    124822.0  2020  0.0  0.0  0.0  2.0  2.0  0.0  0.0  1.0  0.0

[43928 rows x 11 columns]

In [16]:
df_mental.to_csv('mental_python.csv', index=False)